

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 667)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.textEdit.setFont(font)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout.addWidget(self.textEdit, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menunew_file = QtWidgets.QMenu(self.menubar)
        self.menunew_file.setObjectName("menunew_file")
        self.menuedit = QtWidgets.QMenu(self.menubar)
        self.menuedit.setObjectName("menuedit")
        self.menuveiw = QtWidgets.QMenu(self.menubar)
        self.menuveiw.setObjectName("menuveiw")
        self.menufont_size = QtWidgets.QMenu(self.menuveiw)
        self.menufont_size.setObjectName("menufont_size")
        self.menufont_color = QtWidgets.QMenu(self.menuveiw)
        self.menufont_color.setObjectName("menufont_color")
        self.menutheme_window = QtWidgets.QMenu(self.menuveiw)
        self.menutheme_window.setObjectName("menutheme_window")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)

        self.actionsave = QtWidgets.QAction(MainWindow)
        self.actionsave.setObjectName("actionsave")
        self.actionsave_as = QtWidgets.QAction(MainWindow)
        self.actionsave_as.setObjectName("actionsave_as")

        self.actionundo = QtWidgets.QAction(MainWindow)
        self.actionundo.setObjectName("actionundo")
        self.actionredo = QtWidgets.QAction(MainWindow)
        self.actionredo.setObjectName("actionredo")
        self.actionnew_file = QtWidgets.QAction(MainWindow)
        self.actionnew_file.setObjectName("actionnew_file")
        self.actionnew_window = QtWidgets.QAction(MainWindow)
        self.actionnew_window.setObjectName("actionnew_window")
        self.actioncopy = QtWidgets.QAction(MainWindow)
        self.actioncopy.setObjectName("actioncopy")
        self.actioncot = QtWidgets.QAction(MainWindow)
        self.actioncot.setObjectName("actioncot")
        self.actionpaste = QtWidgets.QAction(MainWindow)
        self.actionpaste.setObjectName("actionpaste")
        self.actionclear = QtWidgets.QAction(MainWindow)
        self.actionclear.setObjectName("actionclear")
        self.actionredo_2 = QtWidgets.QAction(MainWindow)
        self.actionredo_2.setObjectName("actionredo_2")
        self.actionundo_2 = QtWidgets.QAction(MainWindow)
        self.actionundo_2.setObjectName("actionundo_2")
        self.actionsearch = QtWidgets.QAction(MainWindow)
        self.actionsearch.setObjectName("actionsearch")
        self.actionfind = QtWidgets.QAction(MainWindow)
        self.actionfind.setObjectName("actionfind")
        self.actionfind_of = QtWidgets.QAction(MainWindow)
        self.actionfind_of.setObjectName("actionfind_of")
        self.actionreplace = QtWidgets.QAction(MainWindow)
        self.actionreplace.setObjectName("actionreplace")
        self.actionzoom = QtWidgets.QAction(MainWindow)
        self.actionzoom.setObjectName("actionzoom")
        self.actionzoom_in = QtWidgets.QAction(MainWindow)
        self.actionzoom_in.setObjectName("actionzoom_in")
        self.actionzoom_out = QtWidgets.QAction(MainWindow)
        self.actionzoom_out.setObjectName("actionzoom_out")
        self.actiondefiult = QtWidgets.QAction(MainWindow)
        self.actiondefiult.setObjectName("actiondefiult")
        self.actionfont_size_2 = QtWidgets.QAction(MainWindow)
        self.actionfont_size_2.setObjectName("actionfont_size_2")
        self.actiondark = QtWidgets.QAction(MainWindow)
        self.actiondark.setObjectName("actiondark")
        self.actionlight = QtWidgets.QAction(MainWindow)
        self.actionlight.setObjectName("actionlight")
        self.actionhighlight = QtWidgets.QAction(MainWindow)
        self.actionhighlight.setObjectName("actionhighlight")
        self.actionblue = QtWidgets.QAction(MainWindow)
        self.actionblue.setObjectName("actionblue")
        self.actionred = QtWidgets.QAction(MainWindow)
        self.actionred.setObjectName("actionred")
        self.actionblach = QtWidgets.QAction(MainWindow)
        self.actionblach.setObjectName("actionblach")
        self.actionwhite = QtWidgets.QAction(MainWindow)
        self.actionwhite.setObjectName("actionwhite")
        self.actionred_2 = QtWidgets.QAction(MainWindow)
        self.actionred_2.setObjectName("actionred_2")
        self.actionblue_2 = QtWidgets.QAction(MainWindow)
        self.actionblue_2.setObjectName("actionblue_2")
        self.actiongreen = QtWidgets.QAction(MainWindow)
        self.actiongreen.setObjectName("actiongreen")
        self.actioncostum_color = QtWidgets.QAction(MainWindow)
        self.actioncostum_color.setObjectName("actioncostum_color")
        self.actionopen_file_2 = QtWidgets.QAction(MainWindow)
        self.actionopen_file_2.setObjectName("actionopen_file_2")
        self.menunew_file.addAction(self.actionopen_file_2)
        self.menunew_file.addAction(self.actionsave)
        self.menunew_file.addAction(self.actionsave_as)
        self.menunew_file.addAction(self.actionnew_file)
        self.menunew_file.addAction(self.actionnew_window)
        self.menuedit.addAction(self.actioncopy)
        self.menuedit.addAction(self.actioncot)
        self.menuedit.addAction(self.actionpaste)
        self.menuedit.addAction(self.actionclear)
        self.menuedit.addAction(self.actionredo_2)
        self.menuedit.addAction(self.actionundo_2)
        self.menuedit.addAction(self.actionsearch)
        self.menuedit.addAction(self.actionfind)
        self.menuedit.addAction(self.actionfind_of)
        self.menuedit.addAction(self.actionreplace)
        self.menufont_size.addAction(self.actionzoom_in)
        self.menufont_size.addAction(self.actionzoom_out)
        self.menufont_size.addAction(self.actiondefiult)
        self.menufont_color.addAction(self.actionblach)
        self.menufont_color.addAction(self.actionwhite)
        self.menufont_color.addAction(self.actionred_2)
        self.menufont_color.addAction(self.actionblue_2)
        self.menufont_color.addAction(self.actiongreen)
        self.menufont_color.addAction(self.actioncostum_color)
        self.menutheme_window.addAction(self.actiondark)
        self.menutheme_window.addAction(self.actionlight)
        self.menutheme_window.addAction(self.actionhighlight)
        self.menutheme_window.addAction(self.actionblue)
        self.menutheme_window.addAction(self.actionred)
        self.menuveiw.addAction(self.menufont_size.menuAction())
        self.menuveiw.addAction(self.menufont_color.menuAction())
        self.menuveiw.addAction(self.menutheme_window.menuAction())
        self.menubar.addAction(self.menunew_file.menuAction())
        self.menubar.addAction(self.menuedit.menuAction())
        self.menubar.addAction(self.menuveiw.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menunew_file.setTitle(_translate("MainWindow", "file"))
        self.menuedit.setTitle(_translate("MainWindow", "edit"))
        self.menuveiw.setTitle(_translate("MainWindow", "veiw"))
        self.menufont_size.setTitle(_translate("MainWindow", "zoom"))
        self.menufont_color.setTitle(_translate("MainWindow", "font-color"))
        self.menutheme_window.setTitle(_translate("MainWindow", "theme window"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionsave.setText(_translate("MainWindow", "save"))
        self.actionsave_as.setText(_translate("MainWindow", "save as"))
        self.actionundo.setText(_translate("MainWindow", "undo"))
        self.actionredo.setText(_translate("MainWindow", "redo"))
        self.actionnew_file.setText(_translate("MainWindow", "new file"))
        self.actionnew_window.setText(_translate("MainWindow", "new window"))
        self.actioncopy.setText(_translate("MainWindow", "copy"))
        self.actioncot.setText(_translate("MainWindow", "cot"))
        self.actionpaste.setText(_translate("MainWindow", "paste"))
        self.actionclear.setText(_translate("MainWindow", "clear"))
        self.actionredo_2.setText(_translate("MainWindow", "redo"))
        self.actionundo_2.setText(_translate("MainWindow", "undo"))
        self.actionsearch.setText(_translate("MainWindow", "search"))
        self.actionfind.setText(_translate("MainWindow", "find"))
        self.actionfind_of.setText(_translate("MainWindow", "find of"))
        self.actionreplace.setText(_translate("MainWindow", "replace"))
        self.actionzoom.setText(_translate("MainWindow", "zoom"))
        self.actionzoom_in.setText(_translate("MainWindow", "zoom in"))
        self.actionzoom_out.setText(_translate("MainWindow", "zoom out"))
        self.actiondefiult.setText(_translate("MainWindow", "defiult"))
        self.actionfont_size_2.setText(_translate("MainWindow", "font-size"))
        self.actiondark.setText(_translate("MainWindow", "dark"))
        self.actionlight.setText(_translate("MainWindow", "light"))
        self.actionhighlight.setText(_translate("MainWindow", "highlight"))
        self.actionblue.setText(_translate("MainWindow", "blue"))
        self.actionred.setText(_translate("MainWindow", "red"))
        self.actionblach.setText(_translate("MainWindow", "blach"))
        self.actionwhite.setText(_translate("MainWindow", "white"))
        self.actionred_2.setText(_translate("MainWindow", "red"))
        self.actionblue_2.setText(_translate("MainWindow", "blue"))
        self.actiongreen.setText(_translate("MainWindow", "green"))
        self.actioncostum_color.setText(_translate("MainWindow", "costum color"))
        self.actionopen_file_2.setText(_translate("MainWindow", "open file"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
